name: backend_deployment

on:
  push:
    branches: [ "deployment" ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions: 
        id-token: write #This is required for requesting the OIDC JWT Token
        contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

    #   - name: Build and push Docker image
    #     run: |
    #       docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} advanceddatabase.azurecr.io
    #       docker build -t advanceddatabase.azurecr.io/advanced-databases-backend:latest Backend/.
    #       docker push advanceddatabase.azurecr.io/advanced-databases-backend:latest

      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_ADVANCED_DATABASES_CREDENTIALS }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          registryUrl: advanceddatabase.azurecr.io
          containerAppName: advanced-databases-backend
          resourceGroup: advanced-databases
          image: advanceddatabase.azurecr.io/advanced-databases-backend:latest
    