name: backend_deployment

on:
  push:
    branches: [ "deployment" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and push Docker image
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }} advanceddatabase.azurecr.io
          docker build -t advanceddatabase.azurecr.io/advanced-databases-backend:latest Backend/.
          docker push advanceddatabase.azurecr.io/advanced-databases-backend:latest
    