name: Build and deploy Node.js app to Azure Web App - tournament-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v4
        with:
          node-version: '14.x'

      - name: npm install and build
        run: |
          cd Frontend/tournament   
          npm install
          npm run build 

      # Zip the build directory
      - name: Zip Release
        uses: TheDoctor0/zip-release@0.6.1
        with:
          filename: release.zip
          path: Frontend/tournament/build/*

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: tournament-app
          path: Frontend/tournament/build/release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4

      - name: List Files
        run: ls -R

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v4
        id: deploy-to-webapp
        with:
          app-name: 'tournament-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHSROFILE_73E8326CE8DF4C4E9DEBDE2216D98D29 }}
          package: release.zip
