name: Build and deploy Node.js app to Azure Web App - tournament-app

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - name: npm install and build
        run: |
          cd Frontend/tournament   
          npm install
          npm run build 

      - name: Zip Release
        run: |
          cd Frontend/tournament/build
          zip -r release.zip *    
          
      - name: List Files
        run: ls -R

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v1
        with:
          name: tournament-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v1
        with:
          name: tournament-app
      - name: List Files
        run: ls -R

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v1
        id: deploy-to-webapp
        with:
          app-name: 'tournament-app'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_73E8326CE8DF4C4E9DEBDE2216D98D29 }}
          package: tournament-app/release.zip
